all : tout

tout :
	pdflatex bloc.tex
	pdflatex chose.tex
	pdflatex gangster.tex
	pdflatex gestionCombat.tex
	pdflatex moteurJeu.tex
	pdflatex objetequipable.tex
	pdflatex objetmarchand.tex
	pdflatex objet.tex
	pdflatex personnage.tex
	pdflatex position.tex
	pdflatex terrain.tex

clean :
	rm -f *.pdf *.log *.aux *.toc *.out *~

